version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - techdome-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=5000
      - DB=mongodb://root:example@mongo:27017/techdome?authSource=admin
    depends_on:
      - mongo
    networks:
      - techdome-network
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - techdome-network
    ports:
      - "3000:3000"

volumes:
  mongo-data:

networks:
  techdome-network:
    driver: bridge
